### ISSUE TITLE
Процедура прошивки

### ISSUE THREAD

**Issue by ieroglif** [p1ne/irz-rootfs#1]
Читаю в файле README
> Поскольку у новой прошивки другое распределение разделов на flash-памяти, прошивка из Web-интерфейса успехом не увенчается. Шить надо через Serial-интерфейс по процедуре, описанной в репозитории
 
О каком именно репозитории речь? В /irz-firmware описания этой процедуры не нашел. Уточните, пожалуйста. (_Боюсь затереть загрузчик неправильной прошивкой_)

**Comment by p1ne** [comment]
Добавил в README ссылку на процедуру прошивки с сайта Radiofid
